# Generated by Django 4.1 on 2023-04-01 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='num_lista',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='partidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=60)),
                ('minutos_jugados', models.IntegerField()),
                ('puntaje', models.IntegerField()),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to='webservice.usuarios')),
            ],
        ),
    ]
