# Generated by Django 4.1 on 2023-04-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_remove_usuarios_grupo_remove_usuarios_num_lista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidas',
            old_name='id_usuarios',
            new_name='id_usuario',
        ),
    ]
