# Generated by Django 4.1 on 2023-04-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_rename_id_usuarios_partidas_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidas',
            old_name='id_usuario',
            new_name='id_usuarios',
        ),
    ]
