# Generated by Django 4.1 on 2023-04-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0007_partidas_intentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidas',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
    ]
